# ===============================
# PostgreSQL
# ===============================

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.globally_quoted_identifiers=true


# ===============================
# Mail (Gmail)
# ===============================

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ===============================
#Sitio del FrontEnd
# ===============================
UrlFrontend=${URL}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



#  API Key de Google AI Studio
gemini.api.key=${API_Google}

# Modelo a usar
gemini.model=gemini-2.0-flash

# Temperatura (0.0 = determinista, 1.0 = más creativo)
gemini.temperature=0.7

# Máximo de tokens en la respuesta
gemini.max-tokens=1024

# Cuántos mensajes recordar por sesión (memoria)
gemini.memory.max-messages=20
